# Generated by Django 3.2 on 2021-05-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(default=None, max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('peso', models.CharField(max_length=3)),
                ('altura', models.CharField(max_length=4)),
                ('data_matricula', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacao', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=300)),
                ('hora_inicio_turma', models.TimeField()),
                ('hora_fim_turma', models.TimeField()),
                ('data_turma', models.DateField()),
                ('alunos', models.ManyToManyField(related_name='_sistema_turma_alunos_+', to='sistema.Aluno')),
                ('instrutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_treino', models.TimeField()),
                ('hora_fim_treino', models.TimeField()),
                ('data_treino', models.DateField()),
                ('rotina', models.CharField(max_length=500)),
                ('cod_aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.aluno')),
                ('cod_instrutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.instrutor')),
            ],
        ),
    ]
