# Generated by Django 3.2 on 2021-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_treino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='hora_fim_treino',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='hora_inicio_treino',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_turma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_fim_turma',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_inicio_turma',
            field=models.TimeField(null=True),
        ),
    ]
