# Generated by Django 3.2 on 2021-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20210504_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, null=True),
        ),
    ]
