# Generated by Django 3.2 on 2021-05-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20210505_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='cod_aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.aluno'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='cod_instrutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.instrutor'),
        ),
    ]
