# Generated by Django 3.2 on 2021-05-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20210505_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.aluno')),
                ('cod_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistema.turma')),
            ],
        ),
    ]
