# Generated by Django 3.2 on 2021-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20210506_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_turma',
            name='cod_aluno',
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='cod_aluno',
            field=models.ManyToManyField(to='sistema.Aluno'),
        ),
    ]
