# Generated by Django 3.2 on 2021-05-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20210506_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(to='sistema.Aluno'),
        ),
        migrations.DeleteModel(
            name='Aluno_Turma',
        ),
    ]
